- .gitignore
연관 티켓 : #10 
be에서 필요한 .gitignore 추가하였습니다.
merge 이후에 프런트에서도 해당 파일에 .gitignore 추가해주세요
@krokerdile @Klomachenko
> chore: be에서 필요한 .gitignore 추가

- be/build.gradle
- be/flyway/src/main/java/com/zzaug/flyway/config/EntityFlywayConfig.java
- be/member/src/main/java/com/zzaug/member/domain/usecase/member/MemberConverter.java
- be/member/src/main/java/com/zzaug/member/domain/usecase/member/MemberUseCase.java
- be/member/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
- be/notification/src/main/java/com/zzaug/notification/domain/usecase/notification/NotificationConverter.java
- be/notification/src/main/java/com/zzaug/notification/domain/usecase/notification/NotificationUseCase.java
- be/notification/src/main/java/com/zzaug/notification/web/controller/v1/notification/NotificationController.java
- be/review/src/main/java/com/zzaug/review/domain/usecase/review/ReviewConverter.java
- be/review/src/main/java/com/zzaug/review/domain/usecase/review/ReviewUseCase.java
- be/review/src/main/java/com/zzaug/review/web/controller/v1/notification/ReviewController.java
- be/security/src/main/java/com/zzaug/security/config/SecurityConfig.java
- be/security/src/main/java/com/zzaug/security/filter/token/TokenAuthenticationFilter.java
🎫 연관 티켓 
---
#14 
🙏 작업
----
- allproject에 spotless가 적용되도록 수정
💁‍♂️ 어떻게?
----
- 기존 allproject 외부에서 선언된 apply gradle을 allproject 내부에서 선언
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [BE/#14] fix: spotless가 각 서브 프로젝트에 적용되지 않는 문제

- fe/tsconfig.json
- fe/vite.config.ts
🎫 연관 티켓 
---
#74
🙏 작업
----
- 디렉토리 구조에 따라서 쉽게 불러오고 구분 할 수 있도록 절대 경로 적용
💁‍♂️ 어떻게?
----
- #71 에 작성 해둔 디렉토리 구조에 맞춰서 개발 진행 중에 자주 불러오게 되는 요소들에 대해서 쉽게 구분하고 확인할 수 있도록 vite.config.ts, tsconfig.json 파일에 절대경로 적용하는 부분 추가
- atom, block을 나눠서 할까 했는데 일단 components 폴더 안에 있어서 적용이 안됨. atom/ , blcok/ 이런식으로 불러오는게 좀 편하지 않을까 생각을 했는데 components/atom, components/block도 괜찮은 거 같아서 일단 @components으로만 적용해뒀음
🙈 PR 참고 사항
----
[참고자료]
https://shape-coding.tistory.com/entry/Vite-TypeScript-Vite-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-%EC%A0%88%EB%8C%80-%EA%B2%BD%EB%A1%9C-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [FE/#74] chore: 절대 경로 적용 완료

- fe/src/components/atom/Input/CommonInput.tsx
- fe/src/components/block/modal/SignInModal.tsx
- fe/src/page/SignUp.tsx
🎫 연관 티켓 
---
#101 
🙏 작업
----
- 회원가입 폼 구현
💁‍♂️ 어떻게?
----
- 공통 컴포넌트 이용
🙈 PR 참고 사항
----
- 지금 value 값을 CommonInput에서 받아오지 못하고 있습니다
그렇다고 해서 value값을 CommonInput에다가 그냥 박아놓긴 그런데,
해결은 사용자 onChange를 이용해볼 생각입니다
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#103] 회원가입 폼 구현 

- fe/src/components/atom/Button/CommonButton.tsx
- fe/src/components/block/modal/AskLoginModal.tsx
- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/page/TestPageThree.tsx
- fe/src/page/TestPageTwo.tsx
- fe/src/routes/router.tsx
🎫 연관 티켓 
---
#111 
🙏 작업
----
- AskLoginModal 구현
💁‍♂️ 어떻게?
----
- 공통 컴포넌트 이용
🙈 PR 참고 사항
----
- CommonButton 공통 컴포넌트를 이용중인데, 내부 value에 값을 할당하지 못하고, 하나하나 다 입력해줘야 합니다.
- 내일 세미나 종료 후 리팩토링 하도록 하겠습니다.
📸 스크린샷
----
🤖 테스트 체크리스트
----
> feat: AskLoginModal 구현

- fe/src/components/atom/Button/ReturnButton.tsx
- fe/src/components/atom/Button/SaveReviewButton.tsx
- fe/src/components/atom/Button/TemporaryStorageButton.tsx
- fe/src/components/block/modal/SaveModal.tsx
- fe/src/page/TestPageThree.tsx
- fe/src/styles/theme.ts
🎫 연관 티켓 
---
#114 
🙏 작업
----
- SaveModal 구현
💁‍♂️ 어떻게?
----
- 공통 컴포넌트 이용
🙈 PR 참고 사항
----
- 버튼을 하나하나 다 만든 의문의 atomic design pattern으로 인해, 새로운 버튼 컴포넌트를 부득이하게 만들었습니다
- SaveReviewButton
- 나머지 버튼들의 경우 크기가 맞지 않아, 버튼 컴포넌트 내부에서 직접 크기를 변경해 주었습니다.  
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#114] SaveModal 구현

- fe/src/components/atom/card/DefaultCard.tsx
- fe/src/components/atom/card/ReviewCard.tsx
- fe/src/components/atom/card/ReviewList.tsx
- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/page/TestPageTwo.tsx
- fe/src/styles/theme.ts
🎫 연관 티켓 
---
#121
🙏 작업
----
- DefaultCard 구현
- ReviewCard 구현
- ReviewCard 안에 들어갈 리뷰 목록 내용 확인 할 수 있도록 ReviewList 구현
💁‍♂️ 어떻게?
----
- 공통 컴포넌트로 카드 구성
- ReviewCard 같은 경우에는 별개로 추가 구성
🙈 PR 참고 사항
----
- Card Height 관련 최소치 정해둬야 될 듯함. 
- 세부적인 내용 넣을 때 조절 필요
- DefaultCard, ReviewCard 둘다 스크롤 관련 내용 추가 필요할 거 같기도..? 
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#121] card components

- be/scripts/restart_all
- be/scripts/run_all
- be/scripts/stop_all
🎫 연관 티켓 
---
#27
🙏 작업
----
- review, member, notification 어플리케이션 실행 스크립트 추가하였습니다. 
💁‍♂️ 어떻게?
----
- bash 를 통해 스크립트를 실행하여 member, review, notification서버가 bootRun을 하도록 구성하였습니다.
- 로그가 밀리는 문제가 있지만 정상적으로 실행됩니다.
로컬 개발 환경 구성 후 (scripts/run-all) 실행
stop_all 실행 시 모든 서버 중지
restart_all 실행 시 모든 서버 재시작
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#27] Feat: 어플리케이션 실행 스크립트 추가

- fe/src/components/atom/card/DefaultCard.tsx
- fe/src/components/atom/card/ReviewCard.tsx
- fe/src/components/block/Content/Question.tsx
- fe/src/components/block/Content/Request.tsx
- fe/src/components/block/Content/Review.tsx
- fe/src/components/block/Content/Setting.tsx
- fe/src/components/block/Search/DefaultInput.tsx
- fe/src/components/block/Search/SearchInput.tsx
- fe/src/components/block/navbar/ContentTab.tsx
- fe/src/components/block/navbar/DefaultTab.tsx
- fe/src/components/layout/GridTemplate.tsx
- fe/src/page/Common.tsx
- fe/src/page/TestPageTwo.tsx
- fe/src/store/useTabStore.ts
🎫 연관 티켓 
---
#135 
🙏 작업
----
- ContentTab 추가
- 검색창 추가
- 페이지별 요소 추가 완료
- GridTemplate Size 조절 
- Review 카드 수정 
💁‍♂️ 어떻게?
----
- 공통 컴포넌트 활용(reviewCard, ContentTab, SearchInput)
- 각 페이지 별 기본 요소 추가
- GridTemplate SideBar랑 높이 맞춰주기
🙈 PR 참고 사항
----
- 세부적으로 작업 조금 더 해야될 필요 있음
- 질문, 리뷰 페이지 넘어가는 라우팅 작업 추가 필요
- lazy,suspense Loading 관련 필요
- Divider 있어야 될거 같기도
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#135] put page content

- fe/package-lock.json
- fe/package.json
- fe/src/components/atom/Input/DefaultInput.tsx
- fe/src/components/atom/card/DefaultCard.tsx
- fe/src/components/atom/card/ReviewCard.tsx
- fe/src/components/block/Content/CreateQuestion.tsx
- fe/src/components/block/Content/CreateReview.tsx
- fe/src/components/block/Content/Question.tsx
- fe/src/components/block/Content/Request.tsx
- fe/src/components/block/Content/Review.tsx
- fe/src/components/block/Editor/BlockNote.tsx
- fe/src/components/block/Search/DefaultInput.tsx
- fe/src/components/block/Search/SearchInput.tsx
- fe/src/components/block/navbar/ContentTab.tsx
- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/page/BlackNoteTest.tsx
- fe/src/page/Common.tsx
- fe/src/routes/router.tsx
🎫 연관 티켓 
---
#153 
🙏 작업
----
- BlockNote 활용해서 에디터 추가하기
- 제목 입력 부분 따로 처리하기
- 세세한 CSS 처리 완료
- 질문 추가 부분 Navigate 처리 하기
💁‍♂️ 어떻게?
----
- DefaultInput 일부 수정(padding 등) 
- router "newQuestion" 추가 
- Common 페이지 newQuestion 부분 추가 완료
- 일부 padding, margin 값 변경 완료 
- 컴포넌트 간의 간격 0.5rem으로 수정 완료 
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#153] create question

- be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListener.java
- be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMapper.java
> 린트가 맞지 않은 rabbitmq 모듈의 파일이 있어 PR 합니다.

- fe/src/components/atom/Button/DefaultButton.tsx
- fe/src/components/atom/Button/GreyButton.tsx
- fe/src/components/block/navbar/ContentTab.tsx
- fe/src/components/block/navbar/DefaultTab.tsx
🎫 연관 티켓 
---
#181 
🙏 작업
----
- 저번 Button 리팩터링(#151)의 Button 컴포넌트들을 활용하여 @krokerdile 현우님이 작업해놓은 페이지들에서의 버튼을 대체하였습니다.
💁‍♂️ 어떻게?
----
```javascript
interface DefaultButtonProps {
children?: React.ReactNode;
width?: number | string;
height?: number | string;
color?: ColorType;
fontSize?: FontSizeType;
backgroundColor?: BackgroundColorType;
borderColor?: borderColorType;
onClick?: MouseEventHandler<HTMLButtonElement>;
padding?: number | string;
cursor?: string;
isActive?: boolean;
isTabButton?: boolean;
}
```
- 현재 수정한 페이지 버튼의 경우 'isActive' 속성을 통해, 스타일을 변경해주고, 내부 로직을 변경해주게 됩니다.
- 해당 스타일, 내부 로직 변경이 용이하도록 DefaultButton, GreyButton에 각각 위와 같이 isActive를 추가해주었고, DefaultButton의 경우엔 isTabButton을 추가하여, Tab에 있는 버튼일 경우에만 isActive의 속성이 적용되도록 작업하였습니다. 자세한 내용은 아래 코드를 첨부하겠습니다.
```javascript
<NavItem …
```
> [FE/181] Button Components 대체 리팩터링

- fe/.prettierignore
- fe/index.html
- fe/src/components/atom/Button/DefaultButton.tsx
- fe/src/components/block/modal/ErrorModal.tsx
- fe/src/page/NotFound.tsx
- fe/src/routes/router.tsx
- fe/tsconfig.json
🎫 연관 티켓 
---
#186
🙏 작업
----
- notfound 페이지
- 해당 페이지에 에러 페이지까지 포함해서 작업
💁‍♂️ 어떻게?
----
- router 상으로 /*으로 들어오는 녀석들 NotFound/Error 페이지로 열리도록 작업 완료
🙈 PR 참고 사항
----
📸 스크린샷
----
이미지 추가 예정(갑자기 추가가 안되서 나중에 하는 걸루) 
🤖 테스트 체크리스트
----
> [feat/#186] feat: ErrorModal 추가

- fe/src/api/axios.ts
- fe/src/api/commentApi.ts
- fe/src/api/memberApi.ts
- fe/src/api/notificationApi.ts
- fe/src/api/questionApi.ts
- fe/src/api/reviewApi.ts
🎫 연관 티켓 
---
#154 
🙏 작업
----
- commment, member, question, notification, review로 나눠서 작업 진행
- question, review 기준이 조금 애매한 녀석들은 일단 question으로 넣어둠 
💁‍♂️ 어떻게?
----
- axios api 형식으로 작성
- 주석으로 어떤 API + [Rest API Method] 달아뒀음
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [fe/#154] api 명세서 기반 axois api 작성 완료

- fe/src/components/atom/Input/CustomInput.tsx
- fe/src/components/block/modal/LoginModal.tsx
🎫 연관 티켓 
---
#214 
🙏 작업
----
- 로그인 페이지에 유효성 검사를 구현하였습니다 
💁‍♂️ 어떻게?
----
```js
const [email, setEmail] = useState('');
const [password, setPassword] = useState('');
const validateForm = () => {
if (email.trim() === '') {
alert('아이디 입력하셈');
} else if (password.trim() === '') {
alert('비밀번호 입력하셈');
} else if (password.trim().length < 8 || !/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/.test(password)) {
alert('비밀번호는 8글자 이상, 영문, 숫자, 특수문자 사용');
} else {
// 모든 조건을 통과하면 로그인 처리 또는 다른 작업 수행
alert('로그인 성공');
}
};
```
- trim 을 통해 앞뒤 공백제거를 통한 정확한 유효성 검사를 고려했습니다.
- 비밀번호의 경우 8글자 이상, 영문, 숫자, 특수문자 사용의 정규표현식을 사용하였습니다.
- 이후 로그인 성공시 진행 로직은 else 내부에 넣어 진행하면 됩니다.
```js
<CustomInput
width={22}
height={3}
type="email"
placeholder="아이디 입력"
fontSize="base"
onChange={(e: …
```
> [Fe/#214] loginpage 유효성 검사 구현

- fe/src/components/block/modal/SignInModal.tsx
🎫 연관 티켓 
---
#216 
🙏 작업
----
- 회원가입 페이지에 유효성 검사를 구현하였습니다 
💁‍♂️ 어떻게?
----
```js
const [email, setEmail] = useState('');
const [password, setPassword] = useState('');
const [passwordConfirm, setPasswordConfirm] = useState('');
const validateForm = () => {
if (email.trim() === '') {
alert('아이디 입력하셈');
} else if (password.trim() === '') {
alert('비밀번호 입력하셈');
} else if (passwordConfirm.trim() === '') {
alert('비밀번호확인 입력하셈');
} else if (password.trim().length < 8 || !/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/.test(password)) {
alert('비밀번호는 8글자 이상, 영문, 숫자, 특수문자 사용');
} else if (!(password === passwordConfirm)) {
alert('확인이랑 비밀번호가 다름');
} 
else {
// 모든 조건을 통과하면 로그인 처리 또는 다른 작업 수행
alert('로그인 성공');
}
};
```
- trim 을 통해 앞뒤 공백제거를 통한 정확한 유효성 검사를 고려했습니다.
- 비밀번호의 경우 8글자 이상, 영문, 숫자, …
> [Fe/#216] signuppage 유효성 검사 구현

- fe/src/components/block/modal/RegisterEmailModal.tsx
🎫 연관 티켓 
---
#218 
🙏 작업
----
- 이메일 등록하기 페이지에 유효성 검사를 구현하였습니다 
💁‍♂️ 어떻게?
----
```js
const [email, setEmail] = useState('');
const validateForm = () => {
if (email.trim() === '') {
alert('이메일 입력하셈');
} else if (email.trim().length < 8 || !/[a-z0-9]+@[a-z]+\.[a-z]{2,3}/.test(email)) {
alert('이메일 형식으로 입력해주세요');
} else {
// 모든 조건을 통과하면 로그인 처리 또는 다른 작업 수행
alert('등록하기 성공');
}
};
```
- trim 을 통해 앞뒤 공백제거를 통한 정확한 유효성 검사를 고려했습니다.
- 이메일 형식 검증 또한 정규표현식을 이용해 구현하였습니다
- 로그인 페이지(#214)와 같은 형식으로 input 값을 받고, onClick을 통해 실행하였습니다
🙈 PR 참고 사항
----
- 없습니다.
📸 스크린샷
----
- 이메일 유효성 검사
- 성공시
🤖 테스트 체크리스트
----
> [Fe/#216] registerEmailPage 유효성 검사 구현

- be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListener.java
- be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMapper.java
- be/review-api/src/main/java/com/zzaug/review/web/controller/v1/review/ReviewController.java
> [Be/#233] Chore: 린트 적용되지 않은 파일들 린트 적용하였습니다.

- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/page/Common.tsx
- fe/src/routes/router.tsx
- fe/src/store/useTabStore.ts
🎫 연관 티켓 
---
#244 
🙏 작업
----
- router 주소 기준으로 sideBar의 TabType 변경 되도록 작업 진행
💁‍♂️ 어떻게?
----
- 관련된 파일 전체 수정 - router, sideBar, common 등
🙈 PR 참고 사항
----
- 이슈에 자세하게 작성해뒀습니다. 
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/#244] router 방식, Refer 적용을 위해서 수정

- be/web/build.gradle
- be/web/src/main/resources/logback-spring.xml
🎫 연관 티켓 
---
#171
🙏 작업
----
-  웹 로깅을 위한 설정을 추가하였습니다.
💁‍♂️ 어떻게?
----
logback logstash encoder 의존성을 추가하였습니다.
`logback-spring.xml`을 통해 로그 관련 설정을 하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#171] Feat: web logging

- be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRabbiMQConfig.java
🎫 연관 티켓 
---
#284
🙏 작업
----
-`@RabbitListener`를 활용하여 RabbitListener를 구현할 수 있도록 합니다. 
💁‍♂️ 어떻게?
----
**[AS-IS]**
`@EnableAutoConfiguration(exclude = RabbitAutoConfiguration.class)` 때문에
`@RabbitListener`를 사용하려 RabbitListener를 생성할 수 없었습니다.
🙈 PR 참고 사항
----
`@EnableRabbit`을 설정에 추가하여 `@Import(RabbitListenerConfigurationSelector.class)`가 추가 될 수 있도록 합니다.
이를 통해 `RabbitBootstrapConfiguration` 실행되어 `@RabbitListener`를 통해 RabbitListener를 생성할 수 있게 됩니다.
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [BE/#284] Feat: 추가 EnableRabbit

- fe/src/components/block/modal/ReviewShowModal.tsx
- fe/src/page/TestPageThree.tsx
- fe/src/routes/router.tsx
🎫 연관 티켓 
---
#301  
🙏 작업
----
- 리뷰어가 리뷰를 작성할 모달인 ReviewShowModal를 구현합니다
💁‍♂️ 어떻게?
----
- 공통 컴포넌트 이용
🙈 PR 참고 사항
----
- react-markdown 라이브러리를 삭제하였습니다
- react-md-editor 라이브러리를 적용하였습니다
- 적용 이유는 추후 작성해 이슈를 연계해 놓도록 하겠습니다  
- ReviewWriteModal에서 리뷰어가 작성한 값이 이 ReviewShowModal로 전송되어 보여집니다
- store에 저장된 리뷰값이 여기에 보여지도록 합니다
- 현재는 `<MDEditor.Markdown />`을 통해서 preview를 제공하는데,
화면이 작게 보일 수 있다는 단점이 존재합니다.
- 추후 툴바 혹은 다른 옵션을 이용해 큰 화면에서 볼 수 있도록 적용해볼 예정입니다.
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fe/301] ReviewShowModal 구현

- be/member-api/src/main/java/com/zzaug/member/persistence/support/transaction/UseCaseTransactional.java
- be/security/src/main/java/com/zzaug/security/persistence/transaction/SecurityTransactional.java
🎫 연관 티켓 
---
#290
🙏 작업
----
- 커스텀 Transactional 적용되지 않는 문제 해결
💁‍♂️ 어떻게?
----
**[AS-IS]**
`@XXTransactional`에서 default 값을 명시하지 않아 Transactional이 적용되지 않았습니다.
**[TO-BE]**
`@XXTransactional`에서 default 값을 명시하고 `@Transactional`의 다른 요소 역시 선언하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#290] Fix: custom transactional

- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollBlackTokenCacheServiceImpl.java
- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollTokenCacheService.java
- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollWhiteAccessTokenCacheServiceImpl.java
- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollWhiteTokenCacheServiceImpl.java
- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/ReplaceTokenCacheService.java
- be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/ReplaceWhiteAccessTokenCacheServiceImpl.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCase.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/EmailAuthUseCase.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/LoginUseCase.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/PostMemberUseCase.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/RenewalTokenUseCase.java
- be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCase.java
- be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/security/UMockEnrollTokenCacheService.java
- be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/security/UMockReplaceTokenCacheService.java
- be/security/src/main/java/com/zzaug/security/redis/auth/BlackAuthTokenHash.java
🎫 연관 티켓 
---
#315
🙏 작업
----
- WhiteAuthToken에 memberId가 추가됨에 따른 수정
💁‍♂️ 어떻게?
----
WhiteAuthToken을 다루는 서비스의 파라미터에 memberId가 추가되었습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#315] Refactor: white token add memberId effect

- be/member-api/Dockerfile
- be/notification-api/Dockerfile
- be/notification-api/build.gradle
🎫 연관 티켓 
---
#317
🙏 작업
----
- Dockerfile 포트 수정 및 notification-api build docker task 추가
💁‍♂️ 어떻게?
----
Dockerfile을 확인한 결과 서버에 해당하는 포트와 다른 경우가 있어 수정하였고 
notification-api에도 dockerfile을 build하는 task를 추가하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#317] Feat: build docker file

- be/security/src/main/java/com/zzaug/security/entity/log/InvalidTokenAccessEntity.java
🎫 연관 티켓 
---
#318
🙏 작업
----
- InvalidTokenAccessEntity의 token의 타입이 테이블과 달라 생기는 문제 해결
💁‍♂️ 어떻게?
----
@Lob를 통해 타입을 맞추어줬습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Be/#318] Fix: invalidtokenacessentity

- fe/src/components/block/Content/CreateQuestion.tsx
- fe/src/components/block/Content/CreateReview.tsx
- fe/src/components/block/modal/ReviewWriteModal.tsx
- fe/src/components/layout/GridTemplate.tsx
- fe/src/page/Common.tsx
- fe/src/routes/router.tsx
- fe/src/store/useMarkdownStore.ts
- fe/src/store/useQuestionStore.ts
- fe/src/store/useReviewStore.ts
🎫 연관 티켓 
---
#309 
🙏 작업
----
- CreateQuestion
- 질문자의 질문글 작성 기능
- 질문글을 상태에 저장
- CreateReview
- 리뷰어의 리뷰 작성 기능
- 상태에 저장된 질문글을 리뷰 페이지에 Preview 형식으로 게시
- 상태관리
- useQuestionStore - 질문글을 관리합니다
- useReviewStore - 리뷰를 관리합니다
💁‍♂️ 어떻게?
----
- 질문글 작성
```jsx
<MarkdownEditor height={'90%'} value={content} onChange={handleMarkdownChange} />
<ButtonBox>
<DefaultButton width={5.5} height={2.25} onClick={handleSubmit}>
<Text fontSize="sm">게시하기</Text>
</DefaultButton>
</ButtonBox>
</MarkdownBox>
```
```jsx
const useQuestionStore = create((set) => ({
title: '',
content: '',
setContent: (newContent) => set({ content: newContent }),
setTitle: (newTitle) => set({ title: newTitle }),
}));
```
- 위의 useQuestionStore를 선언한 뒤, 마크다운 에디터에 질문자가 입력할 질문글을 `content`로 설정하여 저장
- submit 버튼을 통해 제출(현재는 콘솔에 출력)
- Asker가 작성하여 …
> [Fe/#309] 질문글 작성, 게시하기, 리뷰하기 기능 구현

- fe/src/components/block/modal/ErrorModal.tsx
- fe/src/components/block/modal/LoginModal.tsx
- fe/src/components/block/modal/RegisterEmailModal.tsx
- fe/src/components/block/modal/ShowReviewerModal.tsx
- fe/src/components/block/modal/SignInModal.tsx
- fe/src/page/TestPageThree.tsx
🎫 연관 티켓 
---
#342 
🙏 작업
----
- 저번 lint관련 에러 수정으로 인해 발생한 모달들 디자인을 수정하였습니다.
💁‍♂️ 어떻게?
----
- lint에러 수정하면서 아마, padding값을 자동으로 지정해 주던 default 부분이 변경된 것 같습니다. 해당 부분에 padding 값을 다 설정해줌으로써, 해결하였습니다
🙈 PR 참고 사항
----
```jsx
<CustomInput
type="password"
width={22}
height={3}
padding={1}
placeholder="비밀번호 확인"
onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
setPasswordConfirm(e.target.value)
}
// value=''
/>
```
- 기존 코드엔 저 padding 값이 지정되지 않아 디폴트로 8px씩 들어가고 있었던 것 같습니다.
- (그럼 그전엔 왜 잘 맞는거였지...?) 
📸 스크린샷
----
- 타 모달들도 위와 같이 수정 완료하였습니다
🤖 테스트 체크리스트
----
> [Fe/342] input design refactor

- fe/src/components/block/Content/ReadQuestion.tsx
- fe/src/components/block/modal/ReviewShowModal.tsx
- fe/src/components/layout/GridTemplate.tsx
- fe/src/store/useReviewStore.ts
🎫 연관 티켓 
---
#346 
🙏 작업
----
- Asker가 리뷰가 완료된 리뷰글을 조회하는 경우를 구현했습니다.
💁‍♂️ 어떻게?
----
ReadQuestion
- 상태에 담긴 질문글을 불러옵니다 (UseQuestionStore)
- 상태에 담긴 리뷰를 불러옵니다 (UseReviewStore)
- 클릭에 따라 모달창을 보여주고, 가립니다 (UseMarkdownStore)
🙈 PR 참고 사항
----
```jsx
const { content } = useQuestionStore((state) => state);
```
- 상태에 저장된 질문글을 불러옵니다
```jsx
const { showCodeComment, setShowCodeComment } = useMarkdownStore();
```
- 클릭에 따라 모달창을 보여주고, 가립니다
```jsx
const ReviewShowModal = ({ top }) => {
const { review, setReview, id } = useReviewStore();
const { showCodeComment, setShowCodeComment } = useMarkdownStore();
const handleCloseClick = () => {
setShowCodeComment(false);
};
return (
<div style={{ position: 'absolute', top }}>
<LoginBox>
<EditorBox>
<MDEditor.Markdown source={review} />
</EditorBox>
<ButtonBox> …
```
> [Fe/346] 질문자 리뷰조회(CodeComment)구현

- fe/src/components/atom/Comment/LineCommentView.tsx
- fe/src/components/block/Content/CreateReview.tsx
- fe/src/components/layout/GridTemplate.tsx
- GridTemplated, LineCommectView에 LineComment 리뷰 불러오는 부분 적용 Related to LineComment 적용 #364
> [fe/#364] LineComment 세부 조정

- fe/package-lock.json
- fe/package.json
- fe/src/components/atom/Helmet.tsx
- fe/src/components/atom/card/DefaultCard.tsx
- fe/src/components/atom/card/ReviewList.tsx
- fe/src/components/block/Content/CreateReview.tsx
- fe/src/components/block/Content/Question.tsx
- fe/src/components/block/Content/Review.tsx
- fe/src/components/block/modal/ReviewWriteModal.tsx
- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/hooks/query/question/useGetReviews.ts
- fe/src/hooks/query/question/useGetReviewsOnQuestion.ts
- fe/src/main.tsx
Related to react-helmet-async #363
> [fe/#363] helmet 및 기타 사항 처맄

- fe/src/components/atom/Comment/LineCommentView.tsx
- fe/src/components/atom/card/DefaultCard.tsx
- fe/src/components/block/Content/CreateReview.tsx
- fe/src/components/block/sideBar/SideBar.tsx
- fe/src/components/layout/GridTemplate.tsx
- fe/src/store/useReviewStore.ts
> [Fe/#367] grid template error fix
